name: nomedoprojeto
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^14.7.2
  get_it: ^8.0.3
  url_launcher: ^6.3.1
  http: ^1.3.0
  package_info_plus: ^8.2.0
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  dson_adapter: ^1.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: LabradorA
      fonts:
        - asset: assets/fonts/LabradorA-Medium.ttf
          weight: 500
        - asset: assets/fonts/LabradorA-Regular.ttf
          weight: 400
        - asset: assets/fonts/LabradorA-Bold.ttf
          weight: 700
