// Mocks generated by Mockito 5.4.5 from annotations
// in guia_de_motel_teste/test/ui/home_screen/bloc/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:guia_de_motel_teste/data/http/api_client.dart' as _i2;
import 'package:guia_de_motel_teste/data/repositorys/motels_repository.dart'
    as _i4;
import 'package:guia_de_motel_teste/domain/errors/failure_error.dart' as _i6;
import 'package:guia_de_motel_teste/domain/motels/motel_entity.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClientProtocol_0 extends _i1.SmartFake
    implements _i2.ApiClientProtocol {
  _FakeApiClientProtocol_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MotelsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMotelsRepository extends _i1.Mock implements _i4.MotelsRepository {
  MockMotelsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClientProtocol get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeApiClientProtocol_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.ApiClientProtocol);

  @override
  _i5.Future<_i3.Either<_i6.FailureError, List<_i7.MotelEntity>>> getMotels() =>
      (super.noSuchMethod(
            Invocation.method(#getMotels, []),
            returnValue: _i5.Future<
              _i3.Either<_i6.FailureError, List<_i7.MotelEntity>>
            >.value(
              _FakeEither_1<_i6.FailureError, List<_i7.MotelEntity>>(
                this,
                Invocation.method(#getMotels, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.FailureError, List<_i7.MotelEntity>>>);
}
